'''paths.py: where every file lives. The only place in tools/ that knows the folder layout.

Imported by: everything in tools/
Run directly: no

    setup/                  hand-edited, in git: describes the physical rig
        camera.yml          which camera (its name picks the calibration folder)
        plate.yml           the ArUco marker plate
        projector.json      projector lens + calibrated cam1 (written from TouchDesigner)
        model.json          which model is on the plate
    models/<name>/          one folder per model: STL + model.json
    calibration/<camera>/   generated by the tools, not in git
        intrinsics.yml      the lens          (python -m calibration.camera_lens)
        world_origin.yml    the camera's spot (python -m calibration.set_origin)
    tools/output/           printables and snapshots (not in git)

KinectReader (C++) finds the same files by walking up to the folder that
contains setup/camera.yml, so both sides agree without passing paths around.
'''

import json
from pathlib import Path

import cv2

REPO = Path(__file__).resolve().parents[2]

SETUP_DIR = REPO / "setup"
CAMERA_FILE = SETUP_DIR / "camera.yml"
PLATE_FILE = SETUP_DIR / "plate.yml"
PROJECTOR_FILE = SETUP_DIR / "projector.json"
MODEL_FILE = SETUP_DIR / "model.json"

MODELS_DIR = REPO / "models"
CALIBRATION_DIR = REPO / "calibration"
OUTPUT_DIR = REPO / "tools" / "output"


def camera_name():
    """The `name` in setup/camera.yml, which picks calibration/<name>/."""
    fs = cv2.FileStorage(str(CAMERA_FILE), cv2.FILE_STORAGE_READ)
    if not fs.isOpened():
        raise FileNotFoundError(f"Could not open {CAMERA_FILE}")
    name = fs.getNode("name").string()
    fs.release()
    if not name:
        raise ValueError(f"{CAMERA_FILE} needs a name")
    return name


def calibration_dir(name=None):
    return CALIBRATION_DIR / (name or camera_name())


def intrinsics_file(name=None):
    return calibration_dir(name) / "intrinsics.yml"


def origin_file(name=None):
    return calibration_dir(name) / "world_origin.yml"


def output_file(filename):
    """Where generated images go (tools/output/, not in git)."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    return OUTPUT_DIR / filename


def active_model():
    """The model on the plate: models/<active>/model.json with `stl` made absolute."""
    active = json.loads(MODEL_FILE.read_text())["active"]
    folder = MODELS_DIR / active
    model = json.loads((folder / "model.json").read_text())
    model["folder"] = folder
    model["stl"] = folder / model["stl"]
    return model
